DROP DATABASE IF EXISTS SUELAS;

CREATE DATABASE IF NOT EXISTS SUELAS;

USE SUELAS;

SET GLOBAL time_zone = '-5:00';
SET NAMES utf8;

CREATE TABLE IF NOT EXISTS USUARIOS
(
    ID         INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE     VARCHAR(60)    NOT NULL UNIQUE,
    CEDULA     VARCHAR(20)    NOT NULL UNIQUE,
    CORREO     VARCHAR(60)    NOT NULL UNIQUE,
    TELEFONO   VARCHAR(20)    NOT NULL,
    CONTRASENA VARCHAR(255)   NOT NULL,
    CARGO      VARCHAR(20)    NOT NULL,
    CREATED_AT TIMESTAMP      NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP      NOT NULL DEFAULT NOW() ON UPDATE NOW(),
    ACTIVO     ENUM ('SI', 'NO'),
    SESSION_ID VARCHAR(255) NULL
  ) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS OPERARIOS
(
    ID         INT PRIMARY KEY AUTO_INCREMENT,
    USUARIO_ID INT          NULL,
    TURNO      VARCHAR(30) NOT NULL,
    MATERIAL   VARCHAR(30) NOT NULL,
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS (ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS DUREZA
(
    `ID`     ENUM ('1') NOT NULL UNIQUE,
    `DUREZA` INT        NOT NULL,
    PRIMARY KEY (`ID`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS SUELAS
(
    ID                INT PRIMARY KEY AUTO_INCREMENT,
    REFERENCIA        VARCHAR(60) NOT NULL,
    MARCA             VARCHAR(60) NOT NULL,
    TALLA             INT UNSIGNED NOT NULL,
    MATERIAL          VARCHAR(30) NOT NULL,
    PESO_MAQUINA      INT UNSIGNED NOT NULL DEFAULT '0',
    PESO_IDEAL        INT UNSIGNED NOT NULL DEFAULT '0',
    CAP_EMPAQUETADO   INT UNSIGNED NOT NULL DEFAULT '0'
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS SERIES
(
    ID     INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(60) NOT NULL UNIQUE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS GRUPO_SERIES
(
    ID       INT PRIMARY KEY AUTO_INCREMENT,
    SERIE_ID INT NOT NULL,
    SUELA_ID INT NOT NULL,
    FOREIGN KEY (SERIE_ID) REFERENCES SERIES (ID) ON DELETE CASCADE,
    FOREIGN KEY (SUELA_ID) REFERENCES SUELAS (ID) ON DELETE CASCADE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS MATERIA_PRIMA
(
    ID          INT PRIMARY KEY AUTO_INCREMENT,
    DESCRIPCION VARCHAR(60) NOT NULL UNIQUE,
    MATERIAL    VARCHAR(30) NULL,
    COLOR       VARCHAR(30) NULL,
    DUREZA      INT          NULL,
    EXISTENCIA  FLOAT        NOT NULL DEFAULT 0
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS COLOR
(
    ID     INT PRIMARY KEY AUTO_INCREMENT,
    COLOR  VARCHAR(30) NOT NULL UNIQUE,
    CODIGO VARCHAR(7)  NOT NULL UNIQUE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS CLIENTES
(
    ID            INT PRIMARY KEY AUTO_INCREMENT,
    DOCUMENTO     VARCHAR(10)     NOT NULL,
    DOCUMENTO_NRO VARCHAR(20)     NOT NULL,
    NOMBRE        VARCHAR(60)     NOT NULL UNIQUE,
    TIPO          VARCHAR(10)     NOT NULL,
    CORREO        VARCHAR(40)     NOT NULL,
    TELEFONO      VARCHAR(20)     NOT NULL DEFAULT '0',
    CELULAR       VARCHAR(20)     NOT NULL DEFAULT '0',
    DIRECCION     VARCHAR(80)     NOT NULL,
    ACTIVO        ENUM ('SI', 'NO')
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS STOCK
(
    ID         INT PRIMARY KEY AUTO_INCREMENT,
    CLIENTE_ID INT NOT NULL,
    SUELA_ID   INT NOT NULL,
    COLOR_ID   INT NOT NULL,
    CANTIDAD   INT NOT NULL,
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES (ID),
    FOREIGN KEY (SUELA_ID) REFERENCES SUELAS (ID),
    FOREIGN KEY (COLOR_ID) REFERENCES COLOR (ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS PEDIDOS
(
    ID             INT PRIMARY KEY AUTO_INCREMENT,
    USUARIO_ID     INT      NOT NULL,
    CLIENTE_ID     INT      NOT NULL,
    ESTADO         ENUM ('COMPLETADO', 'PENDIENTE', 'EN ANALISIS')                    DEFAULT 'PENDIENTE',
    PRIORIDAD      ENUM ('BAJA', 'ALTA')                                              DEFAULT 'BAJA',
    FORMA_PAGO     ENUM ('EFECTIVO', 'CREDITO', 'TARJETA', 'CHEQUE', 'TRANSFERENCIA') DEFAULT 'CREDITO',
    FECHA_ESTIMADA DATE     NOT NULL,
    CREATED_AT     DATETIME NOT NULL                                                  DEFAULT NOW(),
    UPDATED_AT     DATETIME NOT NULL                                                  DEFAULT NOW() ON UPDATE NOW(),
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS (ID),
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES (ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS PRODUCCION
(
    ID         INT PRIMARY KEY AUTO_INCREMENT,
    PEDIDO_ID  INT              NOT NULL,
    SUELA_ID   INT              NOT NULL,
    SERIE_ID   INT              NOT NULL,
    COLOR_ID   INT              NOT NULL,
    CANTIDAD   INT              NOT NULL,
    RESTANTE   INT              NOT NULL,
    STOCK      INT              NOT NULL,
    POR_PESAR  INT              NOT NULL,
    PESADO     DECIMAL UNSIGNED NOT NULL,
    DISPONIBLE INT              NOT NULL,
    DESPACHADO INT              NOT NULL,
    URGENTE    INT              NOT NULL,
    ESTADO     ENUM ('COMPLETADO', 'PENDIENTE', 'EN ANALISIS', 'POR DESPACHAR'),
    CREATED_AT DATETIME         NULL,
    FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDOS (ID) ON DELETE CASCADE,
    FOREIGN KEY (SUELA_ID) REFERENCES SUELAS (ID),
    FOREIGN KEY (COLOR_ID) REFERENCES COLOR (ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS SOLICITUD_MATERIAL
(
    ID              INT PRIMARY KEY AUTO_INCREMENT,
    PEDIDO_ID       INT      NOT NULL,
    CLIENTE_ID      INT      NOT NULL,
    ESTADO          ENUM ('PENDIENTE', 'APROBADO') DEFAULT 'PENDIENTE',
    FECHA_SOLICITUD DATETIME NOT NULL              DEFAULT NOW(),
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES (ID),
    FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDOS (ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS MATERIALES_SOLICITADOS
(
    ID                    INT PRIMARY KEY AUTO_INCREMENT,
    SOLICITUD_MATERIAL_ID INT          NOT NULL,
    MATERIAL              VARCHAR(30) NOT NULL,
    COLOR                 VARCHAR(30) NOT NULL,
    CANTIDAD              FLOAT        NOT NULL,
    DUREZA                INT          NOT NULL,
    FOREIGN KEY (SOLICITUD_MATERIAL_ID) REFERENCES SOLICITUD_MATERIAL (ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS MAQUINARIAS
(
    ID         INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE     VARCHAR(60)    NOT NULL UNIQUE,
    COLOR      VARCHAR(30)    NOT NULL,
    MATERIAL   VARCHAR(30)    NOT NULL,
    CAPACIDAD  BIGINT UNSIGNED NOT NULL,
    DISPONIBLE BIGINT UNSIGNED NOT NULL,
    ESTADO     VARCHAR(30)    NOT NULL,
    CASILLEROS INT UNSIGNED    NOT NULL,
    CREATED_AT DATETIME        NOT NULL DEFAULT NOW(),
    UPDATED_AT DATETIME        NOT NULL DEFAULT NOW() ON UPDATE NOW()
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS CASILLEROS
(
    ID            INT PRIMARY KEY AUTO_INCREMENT,
    NUMERO        INT           NOT NULL,
    MAQUINARIA_ID INT           NOT NULL,
    SUELA_ID      INT           NULL,
    COLOR         VARCHAR(30)   NULL,
    ACTIVO        BOOLEAN       NOT NULL DEFAULT 1,
    FOREIGN KEY (MAQUINARIA_ID) REFERENCES MAQUINARIAS (ID) ON DELETE CASCADE,
    FOREIGN KEY (SUELA_ID) REFERENCES SUELAS (ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS FORMULAS
(
    ID       INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE   VARCHAR(60) NOT NULL UNIQUE,
    MATERIAL VARCHAR(30) NOT NULL,
    ESTADO   VARCHAR(30) NOT NULL
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS RECETAS
(
    ID          INT PRIMARY KEY AUTO_INCREMENT,
    FORMULA_ID  INT NOT NULL,
    MATERIAL_ID INT NOT NULL,
    FOREIGN KEY (FORMULA_ID) REFERENCES FORMULAS (ID) ON DELETE CASCADE,
    FOREIGN KEY (MATERIAL_ID) REFERENCES MATERIA_PRIMA (ID) ON DELETE CASCADE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;


CREATE TABLE IF NOT EXISTS ENTREGA_MATERIAL
(
    ID                  INT PRIMARY KEY AUTO_INCREMENT,
    FORMULA_ID          INT            NOT NULL,
    USUARIO_MOLINERO_ID INT            NOT NULL,
    USUARIO_OPERARIO_ID INT            NOT NULL,
    MATERIAL            VARCHAR(30)   NOT NULL,
    TURNO               VARCHAR(30)   NOT NULL,
    TOTAL               FLOAT UNSIGNED NOT NULL,
    FECHA               DATETIME       NOT NULL,
    ESTADO              VARCHAR(30)   NOT NULL,
    FOREIGN KEY (USUARIO_MOLINERO_ID) REFERENCES USUARIOS (ID) ON DELETE CASCADE,
    FOREIGN KEY (USUARIO_OPERARIO_ID) REFERENCES USUARIOS (ID) ON DELETE CASCADE,
    FOREIGN KEY (FORMULA_ID) REFERENCES FORMULAS (ID) ON DELETE CASCADE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;


CREATE TABLE IF NOT EXISTS MATERIALES_ENTREGADOS
(
    ID                  INT PRIMARY KEY AUTO_INCREMENT,
    ENTREGA_MATERIAL_ID INT   NOT NULL,
    MATERIAL_ID         INT   NOT NULL,
    CANTIDAD            FLOAT NOT NULL,
    FOREIGN KEY (ENTREGA_MATERIAL_ID) REFERENCES ENTREGA_MATERIAL (ID) ON DELETE CASCADE,
    FOREIGN KEY (MATERIAL_ID) REFERENCES MATERIA_PRIMA (ID) ON DELETE CASCADE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;


CREATE TABLE IF NOT EXISTS REPORTES
(
    ID                  INT PRIMARY KEY AUTO_INCREMENT,
    USUARIO_OPERARIO_ID INT          NOT NULL,
    FECHA               DATETIME     NOT NULL,
    TURNO               VARCHAR(30) NOT NULL,
    MATERIAL            VARCHAR(30) NOT NULL,
    MATERIA_RECIBIDA    FLOAT        NOT NULL,
    MATERIA_SOBRANTE    FLOAT        NOT NULL,
    COLILLAS            FLOAT        NOT NULL,
    PATAS               FLOAT        NOT NULL,
    VARIOS              FLOAT        NOT NULL,
    PRODUCCION_ACTUAL   FLOAT        NOT NULL,
    ESTADO              ENUM ('PENDIENTE','APROBADO') DEFAULT 'PENDIENTE',
    OBSERVACIONES       TEXT         NULL,
    FOREIGN KEY (USUARIO_OPERARIO_ID) REFERENCES USUARIOS (ID) ON DELETE CASCADE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS AUDITORIA_PED_NOR
(
    ID                    INT PRIMARY KEY AUTO_INCREMENT,
    FECHA_RECIBIDO        DATETIME NOT NULL              DEFAULT NOW(),
    FECHA_ENTREGADO       DATETIME                       DEFAULT NULL,
    ESTADO                ENUM ('PENDIENTE', 'APROBADO') DEFAULT 'PENDIENTE',
    SOLICITUD_MATERIAL_ID INT      NOT NULL,
    FOREIGN KEY (SOLICITUD_MATERIAL_ID) REFERENCES SOLICITUD_MATERIAL (ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS AUDITORIA_PED_PRO
(
    ID                   INT PRIMARY KEY AUTO_INCREMENT,
    FECHA_RECIBIDO       DATETIME NOT NULL              DEFAULT NOW(),
    FECHA_ENTREGADO      DATETIME                       DEFAULT NULL,
    ESTADO               ENUM ('PENDIENTE', 'APROBADO') DEFAULT 'PENDIENTE',
    PRODUCCION_PEDIDO_ID INT      NOT NULL,
    FOREIGN KEY (PRODUCCION_PEDIDO_ID) REFERENCES PRODUCCION (PEDIDO_ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS AUDITORIA_NOR_INV
(
    ID                    INT PRIMARY KEY AUTO_INCREMENT,
    FECHA_RECIBIDO        DATETIME NOT NULL              DEFAULT NOW(),
    FECHA_ENTREGADO       DATETIME                       DEFAULT NULL,
    ESTADO                ENUM ('PENDIENTE', 'APROBADO') DEFAULT 'PENDIENTE',
    SOLICITUD_MATERIAL_ID INT      NOT NULL,
    FOREIGN KEY (SOLICITUD_MATERIAL_ID) REFERENCES SOLICITUD_MATERIAL (ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS IMPORTAR_INVENTARIO
(
    ID                    INT PRIMARY KEY AUTO_INCREMENT,
    TURNO                 VARCHAR(80)   NOT NULL,
    TALLA                 VARCHAR(10)   NOT NULL,
    COLOR                 VARCHAR(30)   NOT NULL,
    CANTIDAD              INT           NOT NULL
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;